### ISSUE TITLE
Cannot run program

### ISSUE THREAD

**Issue by connormeredithcu** [DavidRimel/Yoelin_Patten_Rimel_CSCI2270_FINALPROJECT#1]
Hi there. I'm trying to follow your instructions on compiling the program, but I'm having issues. I can't seem to get the makefile to do anything. I'm running Windows 8.1 and I've tried the following commands in Git Bash, Windows Powershell, and Command Prompt while in the directory containing all of your project files:
>make
>./make
>makefile
>./makefile
>DungeonsOfTheCursed_EXE
>./DungeonsOfTheCursed_EXE
but none of the terminals recognize any of these commands. How do I run your program on Windows? Do I need to use a Mac image on the VM?

**Comment by DavidRimel** [comment]
hey ok i thought makefiles where able to run on windows but you have to
install cygwin for it to be able to work.

This is because makefile is a compiling script that i guess is only aviable
to unix like systems, i.e. osx and linux

but if you dont want to do that just git pull from your Ubuntu VM and it
will work

please let me know if you have any questions.

David Rimel

**Comment by DavidRimel** [comment]
so ya just pull once your inside of the Ubuntu VM and in terminal go to the directories live in then type make 

and to run

./DungeonsOfTheCursed_EXE

**Comment by wjvanpatten** [comment]
Alternatively, just replicate the files and dependencies in your particular
IDE. Ie explicit copy and paste.

**Comment by connormeredithcu** [comment]
Awesome, thanks so much! I'll try that as soon as I get a chance.

**Comment by DavidRimel** [comment]
Awsome ya lets us know if this helps im happy to try and get it rubnibg on
your setup

**Comment by DavidRimel** [comment]
also i updated the readme file to reflect this  so pull when u get a chance

**Comment by DavidRimel** [comment]
ok updated the readme to properly show how to compile on different Operating Systems

the command u need is: ( in the same directory the the .cpp and .h files live type in your terminal)

g++ -std=c++11 DungeonsMain.cpp GameBoard.cpp Player.cpp Node.cpp -o DungeonsOfTheCursed_EXE

TO RUN: (in terminal, in same directory you compiled in type)

./DungeonsOfTheCursed_EXE

let me know if this works!
